import { createReadStream } from 'node:fs';
import { mkdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { Readable } from 'node:stream';

/**
 * Storage for the logo and founder photographs managed from Settings. Keys are generated by the server
 * (`logo-<token>.<ext>` / `founder-<id>-<token>.<ext>`); user input never reaches a file-system path.
 * Files are served only through API handlers (never as a static directory).
 */
const KEY_PATTERN = /^(logo|founder-[a-f0-9]{24})-[a-f0-9]{12}\.(png|jpg|webp)$/;

export class BrandingStorage {
  private readonly root: string;
  constructor(root: string) { this.root = path.resolve(root); }

  static isValidKey(key: string): boolean { return KEY_PATTERN.test(key); }

  private resolve(key: string): string {
    if (!KEY_PATTERN.test(key)) throw new Error('Invalid storage key');
    const full = path.resolve(this.root, key);
    if (path.dirname(full) !== this.root) throw new Error('Invalid storage key');
    return full;
  }

  async put(key: string, data: Buffer): Promise<void> {
    await mkdir(this.root, { recursive: true, mode: 0o700 });
    await writeFile(this.resolve(key), data, { flag: 'wx', mode: 0o600 });
  }

  async open(key: string): Promise<{ stream: Readable; size: number } | null> {
    try {
      const full = this.resolve(key);
      const s = await stat(full);
      return { stream: createReadStream(full), size: s.size };
    } catch { return null; }
  }

  async remove(key: string): Promise<void> {
    if (KEY_PATTERN.test(key)) await rm(this.resolve(key), { force: true });
  }
}

let instance: BrandingStorage | undefined;
export function getBrandingStorage(root: string): BrandingStorage { instance ??= new BrandingStorage(root); return instance; }
export function setBrandingStorageForTests(s: BrandingStorage | undefined): void { instance = s; }
