import { createReadStream } from 'node:fs';
import { mkdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { Readable } from 'node:stream';

/**
 * Private receipt storage abstraction. Implementations must never expose public URLs; all reads go
 * through authorised API handlers. Swap `LocalReceiptStorage` for an object-storage implementation
 * (S3/GCS, private bucket) without touching the routes.
 */
export interface ReceiptStorage {
  put(key: string, data: Buffer): Promise<void>;
  open(key: string): Promise<{ stream: Readable; size: number } | null>;
  /** Only used to roll back a failed upload; receipts are otherwise never deleted. */
  remove(key: string): Promise<void>;
}

/** Keys are generated by the server (uuid + canonical extension). Anything else is refused. */
const KEY_PATTERN = /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\.(pdf|jpg|png)$/;

export class LocalReceiptStorage implements ReceiptStorage {
  private readonly root: string;

  constructor(root: string) {
    this.root = path.resolve(root);
  }

  private resolve(key: string): string {
    if (!KEY_PATTERN.test(key)) throw new Error('Invalid storage key');
    const full = path.resolve(this.root, key);
    if (path.dirname(full) !== this.root) throw new Error('Invalid storage key'); // defence in depth
    return full;
  }

  async put(key: string, data: Buffer): Promise<void> {
    await mkdir(this.root, { recursive: true, mode: 0o700 });
    await writeFile(this.resolve(key), data, { flag: 'wx', mode: 0o600 }); // never overwrite
  }

  async open(key: string) {
    const full = this.resolve(key);
    try {
      const s = await stat(full);
      return { stream: createReadStream(full), size: s.size };
    } catch {
      return null;
    }
  }

  async remove(key: string): Promise<void> {
    await rm(this.resolve(key), { force: true });
  }
}

let instance: ReceiptStorage | undefined;
export function getReceiptStorage(root: string): ReceiptStorage {
  instance ??= new LocalReceiptStorage(root);
  return instance;
}
export function setReceiptStorageForTests(s: ReceiptStorage | undefined): void {
  instance = s;
}
